FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/wvs-api ./cmd/wvs-api
COPY migrations/ /migrations/

FROM alpine:3.19
RUN apk add --no-cache ca-certificates
COPY --from=build /bin/wvs-api /usr/local/bin/wvs-api
COPY --from=build /migrations/ /migrations/
ENTRYPOINT ["wvs-api"]
