// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :one
INSERT INTO wvs.audit (wsid, actor, action, request_id, task_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING event_id, ts, wsid, actor, action, request_id, task_id, payload
`

type InsertAuditParams struct {
	Wsid      pgtype.Text `json:"wsid"`
	Actor     []byte      `json:"actor"`
	Action    string      `json:"action"`
	RequestID pgtype.Text `json:"request_id"`
	TaskID    pgtype.Text `json:"task_id"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) (WvsAudit, error) {
	row := q.db.QueryRow(ctx, insertAudit,
		arg.Wsid,
		arg.Actor,
		arg.Action,
		arg.RequestID,
		arg.TaskID,
		arg.Payload,
	)
	var i WvsAudit
	err := row.Scan(
		&i.EventID,
		&i.Ts,
		&i.Wsid,
		&i.Actor,
		&i.Action,
		&i.RequestID,
		&i.TaskID,
		&i.Payload,
	)
	return i, err
}
