// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WvsAudit struct {
	EventID   int64              `json:"event_id"`
	Ts        pgtype.Timestamptz `json:"ts"`
	Wsid      pgtype.Text        `json:"wsid"`
	Actor     []byte             `json:"actor"`
	Action    string             `json:"action"`
	RequestID pgtype.Text        `json:"request_id"`
	TaskID    pgtype.Text        `json:"task_id"`
	Payload   []byte             `json:"payload"`
}

type WvsSnapshot struct {
	SnapshotID string             `json:"snapshot_id"`
	Wsid       string             `json:"wsid"`
	FsPath     string             `json:"fs_path"`
	Message    pgtype.Text        `json:"message"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type WvsTask struct {
	TaskID          string             `json:"task_id"`
	Wsid            string             `json:"wsid"`
	Op              string             `json:"op"`
	Status          string             `json:"status"`
	IdempotencyKey  string             `json:"idempotency_key"`
	RequestHash     string             `json:"request_hash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	Attempt         int32              `json:"attempt"`
	MaxAttempts     int32              `json:"max_attempts"`
	NextRunAt       pgtype.Timestamptz `json:"next_run_at"`
	TimeoutSeconds  int32              `json:"timeout_seconds"`
	CancelRequested bool               `json:"cancel_requested"`
	Params          []byte             `json:"params"`
	Result          []byte             `json:"result"`
	Error           []byte             `json:"error"`
}

type WvsWorkspace struct {
	Wsid              string             `json:"wsid"`
	RootPath          string             `json:"root_path"`
	Owner             string             `json:"owner"`
	State             string             `json:"state"`
	CurrentSnapshotID pgtype.Text        `json:"current_snapshot_id"`
	CurrentPath       string             `json:"current_path"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
