// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO wvs.workspaces (wsid, root_path, owner, state, current_path, created_at, updated_at)
VALUES ($1, $2, $3, 'PROVISIONING', $4, now(), now())
RETURNING wsid, root_path, owner, state, current_snapshot_id, current_path, created_at, updated_at
`

type CreateWorkspaceParams struct {
	Wsid        string `json:"wsid"`
	RootPath    string `json:"root_path"`
	Owner       string `json:"owner"`
	CurrentPath string `json:"current_path"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (WvsWorkspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.Wsid,
		arg.RootPath,
		arg.Owner,
		arg.CurrentPath,
	)
	var i WvsWorkspace
	err := row.Scan(
		&i.Wsid,
		&i.RootPath,
		&i.Owner,
		&i.State,
		&i.CurrentSnapshotID,
		&i.CurrentPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableWorkspace = `-- name: DisableWorkspace :one
UPDATE wvs.workspaces SET state = 'DISABLED', updated_at = now()
WHERE wsid = $1
RETURNING wsid, root_path, owner, state, current_snapshot_id, current_path, created_at, updated_at
`

func (q *Queries) DisableWorkspace(ctx context.Context, wsid string) (WvsWorkspace, error) {
	row := q.db.QueryRow(ctx, disableWorkspace, wsid)
	var i WvsWorkspace
	err := row.Scan(
		&i.Wsid,
		&i.RootPath,
		&i.Owner,
		&i.State,
		&i.CurrentSnapshotID,
		&i.CurrentPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT wsid, root_path, owner, state, current_snapshot_id, current_path, created_at, updated_at FROM wvs.workspaces WHERE wsid = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, wsid string) (WvsWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, wsid)
	var i WvsWorkspace
	err := row.Scan(
		&i.Wsid,
		&i.RootPath,
		&i.Owner,
		&i.State,
		&i.CurrentSnapshotID,
		&i.CurrentPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT wsid, root_path, owner, state, current_snapshot_id, current_path, created_at, updated_at FROM wvs.workspaces
WHERE ($2::timestamptz IS NULL OR created_at < $2::timestamptz)
ORDER BY created_at DESC
LIMIT $1
`

type ListWorkspacesParams struct {
	Limit  int32              `json:"limit"`
	Cursor pgtype.Timestamptz `json:"cursor"`
}

func (q *Queries) ListWorkspaces(ctx context.Context, arg ListWorkspacesParams) ([]WvsWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces, arg.Limit, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WvsWorkspace{}
	for rows.Next() {
		var i WvsWorkspace
		if err := rows.Scan(
			&i.Wsid,
			&i.RootPath,
			&i.Owner,
			&i.State,
			&i.CurrentSnapshotID,
			&i.CurrentPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceCurrent = `-- name: UpdateWorkspaceCurrent :exec
UPDATE wvs.workspaces
SET current_snapshot_id = $2, current_path = $3, updated_at = now()
WHERE wsid = $1
`

type UpdateWorkspaceCurrentParams struct {
	Wsid              string      `json:"wsid"`
	CurrentSnapshotID pgtype.Text `json:"current_snapshot_id"`
	CurrentPath       string      `json:"current_path"`
}

func (q *Queries) UpdateWorkspaceCurrent(ctx context.Context, arg UpdateWorkspaceCurrentParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceCurrent, arg.Wsid, arg.CurrentSnapshotID, arg.CurrentPath)
	return err
}

const updateWorkspaceState = `-- name: UpdateWorkspaceState :exec
UPDATE wvs.workspaces SET state = $2, updated_at = now() WHERE wsid = $1
`

type UpdateWorkspaceStateParams struct {
	Wsid  string `json:"wsid"`
	State string `json:"state"`
}

func (q *Queries) UpdateWorkspaceState(ctx context.Context, arg UpdateWorkspaceStateParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceState, arg.Wsid, arg.State)
	return err
}
